Feat/number slide mobile
WebstepTrondheim/domstol_landingpage pull request #87
Opened 2022-07-19 17:56 UTC by karenhompland

Needed to do some changes on the web design in order to make the mobile version work with "sticky". Sticky does not work with another div around the two text elements for positioning them underneath eachother besides the number element. #79

It does also use some more time now to count to the top for the more dramatic effect. #51

<img width="1440" alt="bilde" src="https://user-images.githubusercontent.com/69513542/179816430-a7ac8c47-2478-4f5b-9500-55e9ab29d8e3.png">
<img width="1440" alt="bilde" src="https://user-images.githubusercontent.com/69513542/179816811-f039e01d-c80b-40ad-a65d-ea9dc364b388.png">

2022-07-20 14:53 UTC, schjoth requested changes
This looks amazing! Especially the mobile version. I have just made some comments on minor things that can be improved :smiley:

2022-07-20 14:53 UTC, schjoth commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
> +            <div className={styles.extraheight}></div>
Would it be possible to achieve the same functionality as the `extraheight` divs, by using the gap property on the parent flexbox?

For example: 
```
@media only screen and (max-width: 1200px) {
    .section {
         gap: 500px;
         padding-top: 500px;
         ...
    }
    ...
```

2022-07-20 14:53 UTC, schjoth commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
>      }, [inView, number])
I am unsure if this is the way to go because every time the number changes the interval will be reapplied. For example if you add the `console.log(number)` as illustrated in this picture: 
![image](https://user-images.githubusercontent.com/27954138/180006621-a41f65ab-2e31-4c28-b0f8-b33ffeb3f81b.png)
you will see that this code runs every time the number changes, which is not very performant. 

Perhaps [this](https://stackoverflow.com/questions/60205544/in-framer-motion-how-to-animate-pure-data-like-a-number-from-0-to-100) would be an adequate solution, as I suppose you could change the `ease`-property, to e.g. "ease-in" so the animation is even slower in the beginning.

This comment is purely related to #51

2022-07-20 14:53 UTC, schjoth commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
> +            >
If you scroll fast on the mobile version the text overlaps with the number and then fades out, which can look a little weird. 

if you would replace the section element with something similar to this, I think we would get the desktop animation to work without interfering with the mobile version:
```
return (  
        <motion.section className={styles.section}  
            initial={{ opacity: 0 }}  
            animate={{ opacity: 1 }}  
            exit={{ opacity: 0 }}  
            transition={{duration: 0.5}}  
        >  
            ....  
        </motion.section>  
```
 and then change the `motion.span` to regular `span`s and a little bottom margin for them both and the number so they don't overlap at the end of the mobile version. Does that make sense?

2022-07-20 20:22 UTC, karenhompland commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
> +            <div className={styles.extraheight}></div>
Good suggestion, but did not work out...

2022-07-26 20:11 UTC, karenhompland commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
>      }, [inView, number])
New method now. Works fine in normal web view and on mobile, but in "mobile view" in web it glitches if you scroll to fast. Did not find any good fix so far, but I guess not that many uses a <1200px width on a laptop/computer, so it should be fine. Any thoughts?

2022-07-26 20:11 UTC, karenhompland commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
> +            >
Fixed.

2022-08-07 14:12 UTC, karenhompland commented on components/slides/domstol/NumberSlide/NumberSlide.tsx
>      }, [inView, number])
Glitch fixed.

2022-08-07 14:13 UTC, karenhompland commented
Now working on Safari and Chrome as well and glitching is fixed :)

2022-08-15 14:38 UTC, schjoth approved these changes

2022-08-15 14:39 UTC, merged